client_config:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
client_config_backend: settings
get_refresh_token: true
oauth_scope:
- https://www.googleapis.com/auth/drive.readonly
save_credentials: true
save_credentials_backend: file
save_credentials_file: C:\Users\lilou\PycharmProjects\PythonProject\Residual_Carbon\credentials.json
