# .streamlit/config.toml
[theme]
primaryColor = "#5D7B6A"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2B"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
